### ISSUE TITLE
PS Script Error

### ISSUE THREAD

**Issue by JZaharakis** [Tools4everBV/HelloID-Conn-SA-Full-AD-AccountDelete#1]
When running createform.ps1 I received the following error:  Invoke-HelloIDDelegatedForm : Cannot bind argument to parameter 'DynamicFormGuid' because it is an empty string. 

![SA_Account_Delete_error](https://user-images.githubusercontent.com/5981796/105220750-2609e680-5b26-11eb-8fc4-ef2be9afdb12.JPG)

**Comment by rschouten97** [comment]
Solved in the current version
